### ISSUE TITLE
The Bing background won't display

### ISSUE THREAD

**Issue by jgreer001** [fastaddons/GroupSpeedDial#152]
**Describe the bug**
I set the background to fully display with when the dials are hidden so I can see the background. It stopped working yesterday. All I get is a white screen when the dials are hidden. I can only see the background behind the dials.
**Steps To Reproduce**

**Expected behavior**

**Device info:**
 - operating system: Windows 10 64 bit
 - Browser and version: Firefox 103.0 but it is ready to update when I restart it.
 - GroupSpeedDial version: I don't know where to look for the version. 

**Additional info**
Add any other info about the problem here.

**Comment by fastaddons** [comment]
Fixed in the 21.3 version released for Firefox moments ago.
Thanks again for reporting this.

**Comment by jgreer001** [comment]
No. Firefox Help says I have the latest Firefox version. It doesn't say
which version it is, though. The problem is still not fixed. When I move
the curser off the speeddial page I do not see the picture, only a white
screen.

Joyce Greer
"Fairy tales do not tell children that dragons exist. Children already know
that dragons exist. Fairy tales tell children that dragons can be killed."
G. K. Chesterton

**Comment by fastaddons** [comment]
You need to check for addon updates, you can do that on page:
```
about:addons
```
There click the gear icon / Check for addon updates

But you should receive update automatically very soon, usually within 24h since the release.
